import { PDFDocument, StandardFonts, rgb } from 'pdf-lib'

export async function generateDisputeLetterPdf(
  userName: string,
  userAddress: string,
  bureauName: string,
  bureauAddress: string,
  subject: string,
  body: string,
): Promise<Buffer> {
  const doc = await PDFDocument.create()
  const font = await doc.embedFont(StandardFonts.Helvetica)
  const fontBold = await doc.embedFont(StandardFonts.HelveticaBold)

  let page = doc.addPage([612, 792])
  const { width, height } = page.getSize()
  let y = height - 56
  const margin = 56
  const lineHeight = 14
  const maxWidth = width - margin * 2

  function wrapText(text: string, maxW: number): string[] {
    const words = text.split(' ')
    const lines: string[] = []
    let current = ''
    for (const word of words) {
      const test = current ? `${current} ${word}` : word
      const w = font.widthOfTextAtSize(test, 11)
      if (w > maxW && current) {
        lines.push(current)
        current = word
      } else {
        current = test
      }
    }
    if (current) lines.push(current)
    return lines
  }

  function addText(text: string, size: number, opts?: { bold?: boolean; color?: number[] }, indent = 0) {
    const f = opts?.bold ? fontBold : font
    const c = opts?.color ? rgb(opts.color[0], opts.color[1], opts.color[2]) : rgb(0.18, 0.23, 0.16)
    if (y < 56) {
      page = doc.addPage([612, 792])
      y = height - 56
    }
    page.drawText(text, { x: margin + indent, y, size, font: f, color: c })
    y -= size * 1.4
  }

  function addWrapped(text: string, size: number, opts?: { bold?: boolean }, indent = 0) {
    const lines = wrapText(text, maxWidth - indent)
    for (const line of lines) {
      addText(line, size, opts, indent)
    }
  }

  addText('SCORELIFT', 14, { bold: true, color: [0.29, 0.49, 0.35] })
  addText('Credit Dispute Letter', 11, { color: [0.42, 0.48, 0.40] })
  y -= 12

  addText('─'.repeat(60), 8, { color: [0.91, 0.90, 0.87] })
  y -= 8

  addText(userName, 12, { bold: true })
  const addrLines = wrapText(userAddress, maxWidth)
  for (const line of addrLines) addText(line, 11)
  y -= 12

  addText(bureauName, 12, { bold: true })
  const bureauLines = wrapText(bureauAddress, maxWidth)
  for (const line of bureauLines) addText(line, 11)
  y -= 12

  addText(`Date: ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })}`, 11)
  y -= 12

  addText('RE: ' + subject, 11, { bold: true })
  y -= 16

  addWrapped('To Whom It May Concern:', 11, { bold: true })
  y -= 8

  const bodyLines = wrapText(body, maxWidth)
  for (const line of bodyLines) addText(line, 11)
  y -= 12

  addWrapped('Sincerely,', 11)
  y -= 20
  addText(userName, 12, { bold: true })

  y -= 24
  addText('─'.repeat(60), 8, { color: [0.91, 0.90, 0.87] })
  addText('Generated by ScoreLift — scorelift.credit', 8, { color: [0.42, 0.48, 0.40] })

  return Buffer.from(await doc.save())
}